.. External links for use project-wide are configured here.
.. _Gateware: https://github.com/myriadrf/LimePSB_RPCM_GW
.. _Board Support Package: https://github.com/myriadrf/LimePSB-RPCM_BSP/tree/master

